# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20170315_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp',
            name='id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
